<?php

namespace App\Domain\Compliance\Services\Tds;

use App\Domain\Audit\Enums\AuditAction;
use App\Domain\Audit\Services\AuditRecorder;
use App\Domain\Compliance\Models\StatutoryReturn;
use App\Domain\Compliance\Models\TdsCertificate;
use App\Domain\Compliance\Models\TdsProfile;
use App\Domain\Identity\Models\User;
use App\Domain\Identity\Scopes\AccessScope;
use App\Domain\Organisation\Models\LegalEntity;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\DB;
use RuntimeException;

/**
 * Form No. 130 (earlier Form 16) — Part L. Prepared only from a VERIFIED annual ledger (every
 * quarter's Form No. 138 acknowledged and matching the ledger), as an immutable snapshot per
 * employee. Part A is issued through TRACES and is referenced, not generated. A regenerated
 * certificate is a new version that supersedes the earlier one.
 */
final class TdsCertificates
{
    public function __construct(private readonly TdsLedgers $ledgers, private readonly AuditRecorder $audit) {}

    /** @return Collection<int, TdsCertificate> */
    public function generate(LegalEntity $entity, string $financialYear, User $actor, ?string $reason = null): Collection
    {
        if (! $actor->hasPermission('compliance.tds.manage')) {
            throw new RuntimeException('You do not have the compliance.tds.manage permission.');
        }

        $year = $this->ledgers->year($entity, $financialYear);
        if ($year->ledger_verified_at === null || ! hash_equals((string) $year->ledger_checksum, $this->ledgers->checksum($entity, $financialYear))) {
            throw new RuntimeException('Form No. 130 is prepared only from a verified annual ledger; verify the ledger (all four Form No. 138 statements acknowledged) first.');
        }

        $profile = TdsProfile::query()->withoutGlobalScope(AccessScope::class)->with('tan')->where('legal_entity_id', $entity->getKey())->first();
        $statements = StatutoryReturn::query()->where('return_type', 'TDS')->where('legal_entity_id', $entity->getKey())
            ->where('period_key', 'like', "{$financialYear}-Q%")->whereIn('status', [StatutoryReturn::ACKNOWLEDGED, StatutoryReturn::RECONCILED])
            ->get()->mapWithKeys(fn ($r) => [$r->period_key => ['return_id' => $r->id, 'acknowledgement' => $r->acknowledgement_reference, 'external_reference' => $r->external_reference]]);

        return DB::transaction(function () use ($entity, $financialYear, $actor, $reason, $year, $profile, $statements) {
            $created = collect();

            foreach ($this->ledgers->active($entity, $financialYear)->groupBy('employee_id') as $employeeId => $rows) {
                $last = $rows->sortBy('month')->last();
                $previous = TdsCertificate::query()->withoutGlobalScope(AccessScope::class)->where('employee_id', $employeeId)->where('legal_entity_id', $entity->getKey())
                    ->where('financial_year', $financialYear)->orderByDesc('version')->first();

                $snapshot = [
                    'form' => ['code' => 'FORM_130', 'legacy_code' => 'FORM_16', 'act_section' => config('peopleos.compliance.formats.TDS_FORM_138.section_code')],
                    'part_a' => [
                        'source' => 'Issued through TRACES; not generated by PeopleOS.',
                        'deductor' => ['legal_name' => $entity->legal_name, 'tan_last4' => $profile?->tan?->registration_number_last4, 'responsible_person' => $profile?->responsible_person_name, 'designation' => $profile?->responsible_person_designation],
                        'employee' => ['employee_id' => (int) $employeeId, 'name' => $last->employee?->person?->display_name, 'pan_last4' => $last->employee?->statutoryDetail?->pan ? substr((string) $last->employee->statutoryDetail->pan, -4) : null],
                        'quarterly_statements' => $statements->all(),
                        'tds_by_quarter' => $rows->groupBy('quarter')->map(fn ($q) => round((float) $q->sum('tds_deducted'), 2))->all(),
                    ],
                    'part_b' => [
                        'gross_salary' => round((float) $rows->sum('gross'), 2),
                        'taxable_salary_paid' => round((float) $rows->sum('taxable_earnings'), 2),
                        'regime' => $last->tax_regime,
                        'computation' => collect($last->basis ?? [])->only(['projected_gross', 'hra_exempt', 'standard_deduction', 'chapter_via', 'taxable_income', 'tax_before_rebate', 'rebate', 'surcharge', 'cess', 'annual_tax'])->all(),
                        'tds_deducted' => round((float) $rows->sum('tds_deducted'), 2),
                    ],
                    'ledger_rows' => $rows->pluck('id')->values()->all(),
                    'rule_versions' => $rows->pluck('rule_version', 'compliance_rule_id')->all(),
                    'notes' => ['Prepared from the verified annual ledger. The official certificate layout has not been verified; this is not a filing-ready certificate.'],
                ];

                if ($previous !== null && hash_equals($previous->snapshot_checksum, hash('sha256', (string) json_encode($snapshot)))) {
                    continue; // unchanged
                }

                $certificate = TdsCertificate::query()->create([
                    'legal_entity_id' => $entity->getKey(),
                    'employee_id' => (int) $employeeId,
                    'tds_financial_year_id' => $year->getKey(),
                    'financial_year' => $financialYear,
                    'code' => 'FORM_130',
                    'legacy_code' => 'FORM_16',
                    'version' => ($previous?->version ?? 0) + 1,
                    'status' => 'generated',
                    'snapshot' => $snapshot,
                    'ledger_checksum' => $year->ledger_checksum,
                    'supersedes_id' => $previous?->getKey(),
                    'generated_by' => $actor->getKey(),
                    'generated_at' => now(),
                    'reason' => $reason,
                ]);
                $previous?->update(['status' => 'superseded']);

                $this->audit->record(AuditAction::StatutoryOutputCreated, 'compliance', $certificate, [], $reason, metadata: ['form' => 'FORM_130', 'legacy_form' => 'FORM_16', 'financial_year' => $financialYear, 'version' => $certificate->version], entityLabel: "Form No. 130 {$financialYear} v{$certificate->version}", actor: $actor);
                $created->push($certificate);
            }

            return $created;
        });
    }

    /** Record that the certificate was issued to the employee (with the TRACES certificate number when known). */
    public function issue(TdsCertificate $certificate, User $actor, ?string $certificateNumber = null): TdsCertificate
    {
        if (! $actor->hasPermission('compliance.tds.manage')) {
            throw new RuntimeException('You do not have the compliance.tds.manage permission.');
        }
        if ($certificate->status !== 'generated') {
            throw new RuntimeException("A {$certificate->status} certificate cannot be issued.");
        }
        if ((int) $certificate->generated_by === (int) $actor->getKey()) {
            throw new RuntimeException('Separation of duties: the person who prepared the certificate cannot issue it.');
        }

        $certificate->update(['status' => 'issued', 'issued_by' => $actor->getKey(), 'issued_at' => now(), 'certificate_number' => $certificateNumber]);
        $this->audit->record(AuditAction::StatutoryOutputApproved, 'compliance', $certificate, [['field' => 'status', 'before' => 'generated', 'after' => 'issued', 'sensitive' => false]], null, metadata: ['form' => 'FORM_130', 'certificate_number' => $certificateNumber], actor: $actor);

        return $certificate;
    }
}
