<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Phase 14 AI assistive controls: every interaction records whether its text was generated by a
 * language model (shown as "AI-generated"), and what the data policy did before anything left
 * PeopleOS (policy, removed / redacted counts, whether a provider was called). No content is added.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::table('ai_interactions', function (Blueprint $table) {
            $table->boolean('ai_generated')->default(false)->after('is_inference');
            $table->json('data_policy')->nullable()->after('ai_generated');
        });
    }

    public function down(): void
    {
        Schema::table('ai_interactions', function (Blueprint $table) {
            $table->dropColumn(['ai_generated', 'data_policy']);
        });
    }
};
